import { z } from 'zod';
import { db,today,addDays } from '../db.js';
import { invoiceStatus,quoteStatus } from './commercial.js';
import { lineTotal,ratio } from '../../shared/money.js';
import { lineSchema } from '../../shared/contracts.js';

const sum=(rows,key)=>rows.reduce((n,r)=>n+r[key],0);
const ranges=z.object({period:z.enum(['7d','30d','3m','year','custom']).default('year'),from:z.string().optional(),to:z.string().optional()});
function range(query){const q=ranges.parse(query),now=today();let from=now.slice(0,4)+'-01-01';if(q.period==='7d')from=addDays(now,-6);if(q.period==='30d')from=addDays(now,-29);if(q.period==='3m')from=addDays(now,-89);if(q.period==='custom'&&q.from&&q.to){if(!/^\d{4}-\d{2}-\d{2}$/.test(q.from)||!/^\d{4}-\d{2}-\d{2}$/.test(q.to)||q.to<q.from||q.to>addDays(q.from,1096))throw Object.assign(new Error('Choisissez une période valide de 3 ans maximum.'),{statusCode:400});return {from:q.from,to:q.to};}return {from,to:now};}
function invoiceNet(i){return i.items.reduce((n,item)=>n+lineTotal(lineSchema.parse(item),i.discountBps).net,0);}
export async function getEvents(){
  const [quotes,projects,invoices,expenses,subscriptions]=await Promise.all([db.quote.findMany({where:{status:{in:['sent','viewed']}},include:{client:true}}),db.project.findMany({where:{status:{not:'archived'}},include:{client:true}}),db.invoice.findMany({where:{status:{notIn:['draft','cancelled']}},include:{client:true,payments:true}}),db.expense.findMany({where:{paid:false}}),db.subscription.findMany({where:{active:true},include:{client:true}})]);
  return [
    ...quotes.map(q=>({id:`quote-${q.id}`,type:'quotes',entityId:q.id,date:q.validUntil,title:`Devis · ${q.client.name}`,detail:q.reference,amountCents:q.totalCents,status:quoteStatus(q)})),
    ...projects.flatMap(p=>[{id:`start-${p.id}`,type:'projects',entityId:p.id,date:p.startDate,title:`Début · ${p.title}`,detail:p.client.name,status:p.status},...(!['completed','delivered'].includes(p.status)?[{id:`project-${p.id}`,type:'projects',entityId:p.id,date:p.dueDate,title:`Livraison · ${p.title}`,detail:p.client.name,status:p.status}]:[])]),
    ...invoices.filter(i=>invoiceStatus(i)!=='paid').map(i=>({id:`invoice-${i.id}`,type:'invoices',entityId:i.id,date:i.dueDate,title:`Paiement · ${i.client.name}`,detail:i.reference,amountCents:i.totalCents-sum(i.payments,'amountCents'),status:invoiceStatus(i)})),
    ...expenses.map(e=>({id:`expense-${e.id}`,type:'expenses',entityId:e.id,date:e.dueDate,title:e.supplier,detail:'Facture fournisseur à payer',amountCents:e.totalCents,status:'pending'})),
    ...subscriptions.map(s=>({id:`subscription-${s.id}`,type:'subscriptions',entityId:s.id,date:s.nextDate,title:s.name,detail:s.client.name,amountCents:s.amountCents,status:'active'}))
  ].sort((a,b)=>a.date.localeCompare(b.date));
}
export async function reporting(app){
  app.get('/api/dashboard',async(req)=>{
    const {from,to}=range(req.query),now=today(),month=now.slice(0,7),year=now.slice(0,4);
    const [payments,invoices,expenses,quotes,projects,subscriptions,clients,activity]=await Promise.all([
      db.payment.findMany({include:{invoice:{include:{items:true}},project:{include:{items:true}}}}),db.invoice.findMany({include:{items:true,payments:true,client:true}}),db.expense.findMany(),db.quote.findMany(),db.project.findMany({include:{client:true,payments:true,tasks:true}}),db.subscription.findMany({where:{active:true},include:{client:true}}),db.client.findMany({select:{createdAt:true}}),db.activityLog.findMany({orderBy:{createdAt:'desc'},take:8})
    ]);
    const issued=invoices.filter(i=>!['draft','cancelled'].includes(i.status));
    const periodPayments=payments.filter(p=>p.date>=from&&p.date<=to),periodExpenses=expenses.filter(e=>e.date>=from&&e.date<=to);
    const receivable=issued.filter(i=>invoiceStatus(i)!=='paid').map(i=>({...i,status:invoiceStatus(i),remainingCents:i.totalCents-sum(i.payments,'amountCents')}));
    const buckets=new Map();const daily=(new Date(to)-new Date(from))/86400000<=35;
    for(let d=from;d<=to;d=addDays(d,1)){const k=daily?d:d.slice(0,7);if(!buckets.has(k))buckets.set(k,{key:k,revenue:0,expenses:0});}
    for(const p of periodPayments){const b=buckets.get(daily?p.date:p.date.slice(0,7));if(b)b.revenue+=p.amountCents;}
    for(const e of periodExpenses){const b=buckets.get(daily?e.date:e.date.slice(0,7));if(b&&e.paid)b.expenses+=e.totalCents;}
    const expenseCategories={},serviceCategories={};
    for(const e of periodExpenses)expenseCategories[e.category]=(expenseCategories[e.category]||0)+e.totalCents;
    for(const p of periodPayments){const source=p.invoice||p.project;if(!source||!source.totalCents)continue;for(const item of source.items.filter(i=>i.frequency==='once'&&(!i.optional||i.selected))){const key=item.category;serviceCategories[key]=(serviceCategories[key]||0)+ratio(lineTotal(lineSchema.parse(item),source.discountBps).net,p.amountCents,source.totalCents);}}
    const transformed=quotes.filter(q=>q.status==='accepted').length,sent=quotes.filter(q=>q.status!=='draft').length;
    const mrr=subscriptions.filter(s=>s.startDate<=now&&(!s.endDate||s.endDate>=now)).reduce((a,s)=>a+(s.frequency==='yearly'?ratio(s.amountCents,1,12):s.amountCents),0);
    const events=await getEvents();
    const outstanding=projects.reduce((s,p)=>s+Math.max(0,p.totalCents-sum(p.payments,'amountCents')),0)+receivable.filter(i=>!i.projectId).reduce((s,i)=>s+i.remainingCents,0);
    return {from,to,stats:{monthlyRevenue:issued.filter(i=>i.issuedDate.startsWith(month)).reduce((a,i)=>a+invoiceNet(i),0),annualRevenue:issued.filter(i=>i.issuedDate.startsWith(year)).reduce((a,i)=>a+invoiceNet(i),0),monthlyCollected:sum(payments.filter(p=>p.date.startsWith(month)),'amountCents'),collected:sum(periodPayments,'amountCents'),remaining:outstanding,quotesSent:sent,quotesAccepted:transformed,conversion:sent?Math.round(transformed/sent*100):0,activeProjects:projects.filter(p=>!['completed','delivered','archived'].includes(p.status)).length,completedProjects:projects.filter(p=>['completed','delivered'].includes(p.status)).length,pendingInvoices:receivable.length,monthlyExpenses:sum(expenses.filter(e=>e.date.startsWith(month)),'totalCents'),expenses:sum(periodExpenses,'totalCents'),cashMargin:sum(periodPayments,'amountCents')-sum(periodExpenses.filter(e=>e.paid),'totalCents'),mrr,arr:mrr*12,newClients:clients.filter(c=>c.createdAt.toISOString().slice(0,10)>=from&&c.createdAt.toISOString().slice(0,10)<=to).length,averageOrder:projects.length?Math.round(sum(projects,'totalCents')/projects.length):0},chart:[...buckets.values()],expenseCategories,serviceCategories,subscriptions,projects:projects.filter(p=>!['archived','delivered','completed'].includes(p.status)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5),upcoming:events.filter(e=>e.date>=addDays(now,-30)&&e.date<=addDays(now,30)&&!e.id.startsWith('start-')).slice(0,7),activity,receivable:receivable.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5)};
  });
  app.get('/api/calendar',async(req)=>{const q=z.object({from:z.string().default(today().slice(0,4)+'-01-01'),to:z.string().default(today().slice(0,4)+'-12-31'),type:z.enum(['all','quotes','projects','invoices','expenses','subscriptions','booking','manual']).default('all'),status:z.string().default('')}).parse(req.query);const events=await getEvents();const [invoices,expenses,entries]=await Promise.all([db.invoice.findMany({where:{issuedDate:{gte:q.from,lte:q.to}},include:{client:true,payments:true}}),db.expense.findMany({where:{date:{gte:q.from,lte:q.to}}}),db.calendarEntry.findMany({where:{date:{gte:q.from,lte:q.to}}})]);const entryEvents=entries.map(c=>({id:`calentry-${c.id}`,type:c.source==='calcom'?'booking':'manual',entityId:c.id,date:c.date,time:c.time||'',endTime:c.endTime||'',title:c.title,detail:c.detail||c.attendeeName||'',amountCents:0,status:c.status||'',source:c.source,editable:c.source==='manual'}));return {events:[...events,...entryEvents].filter(e=>e.date>=q.from&&e.date<=q.to&&(q.type==='all'||q.type===e.type)).sort((a,b)=>a.date.localeCompare(b.date)),archive:[...invoices.map(i=>({id:i.id,type:'invoices',date:i.issuedDate,title:i.client.name,detail:i.reference,amountCents:i.totalCents,status:invoiceStatus(i)})),...expenses.map(e=>({id:e.id,type:'expenses',date:e.date,title:e.supplier,detail:e.category,amountCents:e.totalCents,status:e.paid?'paid':'pending'}))].filter(e=>(q.type==='all'||q.type===e.type)&&(!q.status||(q.status==='unpaid'?e.status!=='paid':e.status===q.status))).sort((a,b)=>b.date.localeCompare(a.date))};});
  app.get('/api/notifications',async(req)=>{const read=await db.notification.findMany({where:{userId:req.user.id}}),keys=new Set(read.map(n=>n.key));return (await getEvents()).filter(e=>!e.id.startsWith('start-')&&e.date<=addDays(today(),7)).map(e=>({...e,key:`${e.id}:${e.date}`,read:keys.has(`${e.id}:${e.date}`)}));});
  app.post('/api/notifications/read',async(req)=>{const {keys}=z.object({keys:z.array(z.string().max(200)).max(500)}).parse(req.body);await db.notification.createMany({data:keys.map(key=>({key,userId:req.user.id})),skipDuplicates:true});return {ok:true};});
  app.get('/api/search',async(req)=>{const {q}=z.object({q:z.string().trim().min(2).max(100)}).parse(req.query);const contains={contains:q};const [clients,projects,quotes,invoices,documents]=await Promise.all([db.client.findMany({where:{OR:[{name:contains},{email:contains}]},take:6}),db.project.findMany({where:{OR:[{title:contains},{client:{name:contains}}]},take:6}),db.quote.findMany({where:{OR:[{title:contains},{reference:contains},{client:{name:contains}}]},take:6}),db.invoice.findMany({where:{OR:[{reference:contains},{client:{name:contains}},{title:contains}]},take:6}),db.document.findMany({where:{OR:[{name:contains},{client:{name:contains}},{project:{title:contains}}]},take:6})]);return [...clients.map(c=>({id:c.id,type:'clients',title:c.name,detail:c.email})),...projects.map(p=>({id:p.id,type:'projects',title:p.title,detail:p.reference})),...quotes.map(p=>({id:p.id,type:'quotes',title:p.title,detail:p.reference})),...invoices.map(p=>({id:p.id,type:'invoices',title:p.title,detail:p.reference})),...documents.map(d=>({id:d.id,type:'documents',title:d.name,detail:d.mime}))];});
}
