<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue';import {useRouter,useRoute,onBeforeRouteLeave} from 'vue-router';import {api,mutate,notify} from '../lib/api.js';import {money,today,addDays} from '../lib/format.js';import {lineSchema,quoteSchema,invoiceSchema} from '../../shared/contracts.js';import {totals,lineTotal,eurosToCents,ratio} from '../../shared/money.js';import PageTitle from '../components/PageTitle.vue';import Icon from '../components/Icon.vue';import CrudForm from '../components/CrudForm.vue';import Modal from '../components/Modal.vue';
const props=defineProps({kind:String,id:String});const router=useRouter(),route=useRoute(),ready=ref(false),busy=ref(false),error=ref(''),clientOpen=ref(false),lookups=ref({clients:[],services:[],settings:{}}),serviceId=ref(''),serviceSearch=ref(''),source=ref(null),saved=ref(false),leave=ref(null);
const isQuote=computed(()=>props.kind==='quotes');const form=ref({clientId:'',title:'',issuedDate:today(),validUntil:addDays(today(),30),dueDate:addDays(today(),30),kind:'final',deposit:'30',discount:'0',conditions:'',legalNotice:'',estimatedDelay:'4 à 6 semaines',proClient:false,notes:'',notesOnPdf:false,items:[]});
const blank=()=>({key:crypto.randomUUID(),name:'',description:'',category:'Sur mesure',section:'Prestations',quantity:'1',price:'0.00',discount:'0',vat:'0',frequency:'once',optional:false,selected:true});
const toUi=i=>({...i,key:crypto.randomUUID(),quantity:String(i.quantityMilli/1000),price:(i.unitCents/100).toFixed(2),discount:String(i.discountBps/100),vat:String(i.vatBps/100)});
function quantityMilli(value){const s=String(value).replace(',','.');if(!/^\d+(\.\d{1,3})?$/.test(s))throw new Error('Quantité invalide (3 décimales maximum).');const [whole,fraction='']=s.split('.');return Number(whole)*1000+Number(fraction.padEnd(3,'0'));}
function lines(){return form.value.items.map((i,position)=>({...i,position,quantityMilli:quantityMilli(i.quantity),unitCents:eurosToCents(String(i.price)),discountBps:eurosToCents(String(i.discount)),vatBps:eurosToCents(String(i.vat))}));}
const calculation=computed(()=>{try{return {value:totals(lines(),eurosToCents(form.value.discount),eurosToCents(form.value.deposit)),error:''};}catch(e){return {value:totals([]),error:e.message};}});
const services=computed(()=>lookups.value.services.filter(s=>s.name.toLowerCase().includes(serviceSearch.value.toLowerCase())));
const maintenanceWarning=computed(()=>form.value.items.some(i=>i.includesMaintenance)&&form.value.items.some(i=>i.category==='Maintenance'&&i.frequency==='monthly'));
function addService(){const s=lookups.value.services.find(s=>s.id===serviceId.value);if(!s)return;form.value.items.push({...blank(),name:s.name,description:s.description,category:s.category.name,section:s.frequency==='once'?'Projet':'Accompagnement',price:(s.unitCents/100).toFixed(2),frequency:isQuote.value?s.frequency:'once',includesMaintenance:s.includesMaintenance});serviceId.value='';}
function move(i,delta){const j=i+delta;if(j<0||j>=form.value.items.length)return;[form.value.items[i],form.value.items[j]]=[form.value.items[j],form.value.items[i]];}
function lineAmount(item){try{return lineTotal({...item,unitCents:eurosToCents(String(item.price)),quantityMilli:quantityMilli(item.quantity),discountBps:eurosToCents(String(item.discount)),vatBps:eurosToCents(String(item.vat))},eurosToCents(form.value.discount)).total;}catch{return 0;}}
function sourceItems(){
  if(!source.value)return;const s=source.value,groups=new Map();
  for(const item of s.items.filter(i=>i.frequency==='once'&&(!i.optional||i.selected))){const net=lineTotal(lineSchema.parse(item),s.discountBps).net;const key=item.vatBps;const group=groups.get(key)||{vatBps:key,net:0,names:[]};group.net+=net;group.names.push(item.name);groups.set(key,group);}
  for(const invoice of s.invoices?.filter(i=>i.status!=='cancelled')||[])for(const item of invoice.items||[]){const group=groups.get(item.vatBps);if(group)group.net-=lineTotal(lineSchema.parse(item),invoice.discountBps).net;}
  form.value.discount='0';form.value.items=[...groups.values()].filter(g=>g.net>0).map(g=>({...blank(),name:`${form.value.kind==='deposit'?'Acompte':form.value.kind==='intermediate'?'Situation intermédiaire':'Solde'} · ${s.title}`,description:g.names.join(' · '),category:'Création de site',section:'Projet',price:((form.value.kind==='deposit'?ratio(g.net,eurosToCents(form.value.deposit),10000):g.net)/100).toFixed(2),vat:String(g.vatBps/100)}));
}
onMounted(async()=>{try{lookups.value=await api('/lookups');const settings=lookups.value.settings;form.value.conditions=settings.conditions;form.value.legalNotice=settings.legalNotice;form.value.deposit=String(settings.depositBps/100);form.value.validUntil=addDays(today(),settings.validDays);
  if(props.id){const r=await api(`/${props.kind}/${props.id}`);if(r.status!=='draft')throw new Error('Ce document est déjà émis et ne peut plus être modifié.');form.value={...form.value,...r,projectId:r.projectId||undefined,quoteId:r.quoteId||undefined,deposit:String((r.depositBps??settings.depositBps)/100),discount:String(r.discountBps/100),items:r.items.map(toUi)};}
  else {if(route.query.client)form.value.clientId=String(route.query.client);
    if(!isQuote.value&&(route.query.project||route.query.quote)){const type=route.query.project?'projects':'quotes',id=String(route.query.project||route.query.quote);let s=await api(`/${type}/${id}`);if(type==='quotes'&&s.project)s=await api('/projects/'+s.project.id);source.value=s;form.value.clientId=s.clientId;form.value.title=s.title;form.value.projectId=s.quoteId?s.id:undefined;form.value.quoteId=s.quoteId||s.id;
      if(s.invoices?.length){source.value.invoices=await Promise.all(s.invoices.map(i=>api('/invoices/'+i.id)));}
      sourceItems();
    }else if(route.query.subscription){const subs=await api('/subscriptions'),s=subs.find(s=>s.id===route.query.subscription);if(s){form.value.clientId=s.clientId;form.value.title=`${s.name} · ${s.nextDate}`;form.value.items=[{...blank(),name:s.name,description:`Période débutant le ${s.nextDate}`,category:s.category,price:(s.amountCents/100).toFixed(2)}];}}
  }
  ready.value=true;
}catch(e){error.value=e.message;}});
async function newClient(c){lookups.value.clients.push(c);form.value.clientId=c.id;clientOpen.value=false;}
async function save(){busy.value=true;error.value='';try{const value={...form.value,depositBps:eurosToCents(form.value.deposit),discountBps:eurosToCents(form.value.discount),items:lines()};const body=(isQuote.value?quoteSchema:invoiceSchema).parse(value);const result=await mutate('/'+props.kind+(props.id?'/'+props.id:''),props.id?'PUT':'POST',body,'Brouillon enregistré.');saved.value=true;router.push(`/${props.kind}/${result.id}`);}catch(e){error.value=e.issues?e.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join(' · '):e.message;}finally{busy.value=false;}}
function key(e){if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();if(!busy.value&&ready.value)save();}}
onMounted(()=>document.addEventListener('keydown',key));onUnmounted(()=>document.removeEventListener('keydown',key));
onBeforeRouteLeave(to=>{if(saved.value||!form.value.items.length)return true;leave.value=to.fullPath;return false;});
function discard(){saved.value=true;router.push(leave.value);}
</script>
<template><RouterLink :to="'/'+kind" class="back-link"><Icon name="ArrowLeft" :size="15"/>Retour aux {{isQuote?'devis':'factures'}}</RouterLink><PageTitle :number="isQuote?'03':'05'" :title="`${id?'MODIFIER LE':'NOUVEAU'} ${isQuote?'DEVIS':'FACTURE'}`" subtitle="Un périmètre précis. Un montant sans surprise."><span class="eyebrow muted">{{id?'BROUILLON':'NOUVEAU BROUILLON'}} · ⌘ S</span></PageTitle><p v-if="error" class="form-error" role="alert" style="margin-bottom:24px">{{error}}</p><div v-if="!ready&&!error" class="skeleton-page"></div><form v-if="ready" @submit.prevent="save" class="builder-layout"><div class="builder-main"><section class="builder-section"><span class="eyebrow">01 / LE CONTEXTE</span><h2>À QUI S’ADRESSE LE PROJET ?</h2><div class="form-grid"><label>Client<select v-model="form.clientId" required><option value="" disabled>Choisir un client</option><option v-for="c in lookups.clients" :key="c.id" :value="c.id">{{c.name}}</option></select></label><div style="align-self:end"><button type="button" class="btn" @click="clientOpen=true"><Icon name="Plus"/>Nouveau client</button></div><label class="span-2">Objet du {{isQuote?'devis':'document'}}<input v-model="form.title" required placeholder="Ex. Refonte du site vitrine"></label><label>Date d’émission<input type="date" v-model="form.issuedDate" required></label><label>{{isQuote?'Valable jusqu’au':'Date d’échéance'}}<input v-if="isQuote" type="date" v-model="form.validUntil" :min="form.issuedDate" required><input v-else type="date" v-model="form.dueDate" :min="form.issuedDate" required></label><label v-if="!isQuote" class="span-2">Type de facture<select v-model="form.kind" @change="sourceItems"><option value="deposit">Facture d’acompte</option><option value="intermediate">Facture intermédiaire</option><option value="final">Facture finale</option></select></label></div><p v-if="source" class="section-note" style="margin-top:20px">Lié à {{source.reference}}. Les factures antérieures sont déduites du solde proposé.</p></section>
<section class="builder-section"><span class="eyebrow">02 / LE PÉRIMÈTRE</span><h2>LES PRESTATIONS.</h2><div class="form-grid"><label>Rechercher dans le catalogue<input v-model="serviceSearch" placeholder="Site, hébergement, maintenance…"></label><label>Ajouter une prestation<select v-model="serviceId" @change="addService"><option value="">Choisir une prestation</option><option v-for="s in services" :key="s.id" :value="s.id">{{s.name}} · {{money(s.unitCents,true)}}{{s.frequency==='monthly'?' / mois':''}}</option></select></label></div><p v-if="maintenanceWarning" class="section-note" style="margin-top:20px">L’hébergement choisi inclut déjà la maintenance. Vérifiez que le suivi mensuel supplémentaire correspond bien à une prestation distincte.</p><div v-for="(item,i) in form.items" :key="item.key" class="quote-line"><div class="line-grid"><label>Prestation<input v-model="item.name" required maxlength="200"></label><label>Quantité<input v-model="item.quantity" inputmode="decimal" required></label><label>Prix HT (€)<input v-model="item.price" inputmode="decimal" required></label><label>Remise (%)<input v-model="item.discount" inputmode="decimal" required></label><label>TVA (%)<input v-model="item.vat" inputmode="decimal" required></label></div><div class="line-details"><label>Description<textarea v-model="item.description" rows="2"/></label><label>Section<input v-model="item.section" required></label><label>Fréquence<select v-model="item.frequency"><option value="once">Unique</option><option v-if="isQuote" value="monthly">Mensuelle</option><option v-if="isQuote" value="yearly">Annuelle</option></select></label></div><div class="line-bottom"><label class="check-label" v-if="isQuote"><input type="checkbox" v-model="item.optional">Option facultative</label><label class="check-label" v-if="item.optional"><input type="checkbox" v-model="item.selected">Incluse dans le total</label><strong>{{money(lineAmount(item),true)}}{{item.frequency==='monthly'?' / mois':item.frequency==='yearly'?' / an':''}}</strong><div class="line-actions"><button class="icon-button" type="button" :disabled="i===0" @click="move(i,-1)" aria-label="Monter la prestation"><Icon name="ChevronLeft" :size="15" style="transform:rotate(90deg)"/></button><button class="icon-button" type="button" :disabled="i===form.items.length-1" @click="move(i,1)" aria-label="Descendre la prestation"><Icon name="ChevronRight" :size="15" style="transform:rotate(90deg)"/></button><button class="icon-button" type="button" @click="form.items.splice(i,1)" aria-label="Retirer cette ligne du brouillon"><Icon name="Trash2" :size="15"/></button></div></div></div><button type="button" class="btn" style="margin-top:20px" @click="form.items.push(blank())"><Icon name="Plus"/>Ligne personnalisée</button></section>
<section class="builder-section"><span class="eyebrow">03 / LES CONDITIONS</span><h2>POSONS LE CADRE.</h2><div class="form-grid"><label>Remise globale (%)<input v-model="form.discount" inputmode="decimal" required></label><label v-if="isQuote||form.kind==='deposit'">Acompte (%)<input v-model="form.deposit" inputmode="decimal" required @change="!isQuote&&sourceItems()"></label><label v-if="isQuote" class="span-2">Délai estimé<input v-model="form.estimatedDelay"></label><label class="span-2">Conditions de paiement<textarea v-model="form.conditions"/></label><label class="span-2">Mentions légales<textarea v-model="form.legalNotice"/></label><label class="check-label span-2"><input type="checkbox" v-model="form.proClient">Client professionnel — imprimer les pénalités de retard et l’indemnité de 40 € (obligatoire en B2B)</label><label v-if="isQuote" class="span-2">Note projet<textarea v-model="form.notes" placeholder="Contexte du projet, précisions pour le client ou pour vous…"/></label><label v-if="isQuote" class="check-label span-2"><input type="checkbox" v-model="form.notesOnPdf">Afficher cette note sur le devis (PDF). Sinon, elle reste interne à Birostweb.</label></div></section></div>
<aside class="builder-summary"><span class="eyebrow">LE RÉCAPITULATIF</span><h2>CLAIR.<br>NET. PRÉCIS.</h2><div class="summary-row"><span>Sous-total HT</span><strong>{{money(calculation.value.subtotal,true)}}</strong></div><div class="summary-row"><span>Remises</span><span>− {{money(calculation.value.discount,true)}}</span></div><div class="summary-row"><span>TVA</span><span>{{money(calculation.value.tax,true)}}</span></div><div class="eyebrow" style="margin-top:22px">TOTAL {{isQuote?'PROJET':''}} TTC</div><div class="summary-total">{{money(calculation.value.total,true)}}</div><template v-if="isQuote"><div class="summary-row"><span>Acompte TTC</span><span>{{money(calculation.value.deposit,true)}}</span></div><div class="summary-row"><span>Solde TTC</span><span>{{money(calculation.value.remaining,true)}}</span></div><div v-if="calculation.value.monthly" class="summary-row"><span>Récurrent TTC</span><span>{{money(calculation.value.monthly,true)}} / mois</span></div><div v-if="calculation.value.yearly" class="summary-row"><span>Récurrent TTC</span><span>{{money(calculation.value.yearly,true)}} / an</span></div></template><p v-if="calculation.error" class="form-error">{{calculation.error}}</p><button class="btn primary full" :disabled="busy||!!calculation.error||!form.items.length">{{busy?'Enregistrement…':'Enregistrer le brouillon'}}<Icon name="ArrowUpRight"/></button><p class="field-note">{{isQuote?'Le PDF sera disponible après enregistrement.':'Le numéro définitif est attribué à l’émission.'}}</p><span class="slash-mark accent" style="margin-top:30px">///</span></aside><div class="mobile-save"><button class="btn primary full" :disabled="busy||!!calculation.error||!form.items.length">{{busy?'Enregistrement…':'Enregistrer le brouillon'}}</button></div></form>
<CrudForm :open="clientOpen" kind="clients" @close="clientOpen=false" @saved="newClient"/><Modal :open="!!leave" title="QUITTER LE BROUILLON ?" @close="leave=null"><p>Les modifications non enregistrées seront perdues.</p><div class="form-actions"><button class="btn" @click="leave=null">Continuer l’édition</button><button class="btn danger" @click="discard">Quitter sans enregistrer</button></div></Modal></template>
