<script setup>
import {ref,onMounted,computed} from 'vue';import {api,session,notify} from '../lib/api.js';import {money,dateLabel} from '../lib/format.js';import {labels} from '../../shared/contracts.js';import Icon from '../components/Icon.vue';import Badge from '../components/Badge.vue';import EmptyState from '../components/EmptyState.vue';import AccountSecurity from '../components/AccountSecurity.vue';
const data=ref(null),error=ref(''),fiche=ref({}),busyFiche=ref(false);
const firstName=computed(()=>session.user?.name?.split(' ')[0]||'');
async function load(){try{error.value='';data.value=await api('/portal');fiche.value={...data.value.referrer};}catch(e){error.value=e.message;}}
async function saveFiche(){busyFiche.value=true;try{const f=fiche.value;await api('/portal/profile',{method:'PATCH',body:{name:f.name,email:f.email,phone:f.phone,address:f.address,siret:f.siret,iban:f.iban,notes:f.notes}});notify('Fiche mise à jour.');await load();}catch(e){notify(e.message,'error');}finally{busyFiche.value=false;}}
onMounted(load);
async function logout(){try{await api('/auth/logout',{method:'POST'});session.user=null;session.csrf='';}catch(e){notify(e.message,'error');}}
</script>
<template><main class="portal"><div class="portal-top"><span class="brand"><span class="brand-mark">b<span>w</span></span>birostweb<span class="accent">.</span></span><div class="row-between" style="gap:16px"><span class="eyebrow muted">ESPACE APPORTEUR</span><button class="icon-button" aria-label="Se déconnecter" title="Se déconnecter" @click="logout"><Icon name="LogOut" :size="16"/></button></div></div>
<p v-if="error" class="form-error">{{error}} <button class="text-button" @click="load">Réessayer</button></p>
<template v-if="data">
<div class="portal-welcome"><span class="eyebrow"><span class="accent">[11]</span> BIROSTWEB / APPORTEUR D’AFFAIRES</span><h1>Bonjour {{firstName}}<span class="accent">.</span></h1><p class="muted">Le suivi des affaires que vous avez apportées à Birostweb et des commissions associées.</p></div>
<section class="metrics-strip"><div><small>À VOUS VERSER</small><strong class="accent">{{money(data.stats.dueCents)}}</strong></div><div><small>EN ATTENTE D’ENCAISSEMENT</small><strong>{{money(data.stats.awaitingCents)}}</strong></div><div><small>DÉJÀ VERSÉ EN {{new Date().getFullYear()}}</small><strong>{{money(data.stats.paidYearCents)}}</strong></div></section>
<section class="panel"><div class="panel-head"><div><span class="eyebrow">VOS COMMISSIONS</span><h2>LE DÉTAIL.</h2></div><span class="eyebrow muted">{{data.commissions.length}} LIGNE{{data.commissions.length>1?'S':''}}</span></div><div class="table-scroll"><table><thead><tr><th>DATE</th><th>CLIENT</th><th>MONTANT ENCAISSÉ HT</th><th>TAUX</th><th>VOTRE COMMISSION</th><th>STATUT</th></tr></thead><tbody><tr v-for="c in data.commissions" :key="c.id"><td>{{dateLabel(c.date,true)}}<div class="table-sub" v-if="c.paidDate">Versée le {{dateLabel(c.paidDate,true)}}</div></td><td>{{c.clientName}}<div class="table-sub" v-if="c.label&&c.label!==c.clientName">{{c.label}}</div></td><td class="mono">{{money(c.baseCents,true)}}</td><td class="mono">{{c.rateBps/100}} %</td><td class="mono">{{money(c.amountCents,true)}}</td><td><Badge :status="c.status"/></td></tr></tbody></table></div><EmptyState v-if="!data.commissions.length" title="Aucune commission pour le moment." description="Elles apparaîtront ici dès qu’une affaire que vous avez apportée sera encaissée."/></section>
<section class="panel" style="margin-top:24px"><div class="panel-head"><div><span class="eyebrow">VOS MISES EN RELATION</span><h2>LES CLIENTS APPORTÉS.</h2></div></div><div class="table-scroll"><table><thead><tr><th>CLIENT</th><th>STATUT</th></tr></thead><tbody><tr v-for="c in data.clients" :key="c.name"><td>{{c.name}}</td><td><Badge :status="c.status"/></td></tr></tbody></table></div><EmptyState v-if="!data.clients.length" title="Aucun client rattaché." description="Les clients que vous mettez en relation apparaîtront ici."/></section>
<section class="panel" style="margin-top:24px"><div class="panel-head"><div><span class="eyebrow">VOTRE FICHE</span><h2>VOS COORDONNÉES.</h2></div></div><form @submit.prevent="saveFiche" style="padding:0 24px 24px"><div class="form-grid"><label class="span-2">Nom / raison sociale<input v-model="fiche.name" required maxlength="200"></label><label>Email<input v-model="fiche.email" type="email"></label><label>Téléphone<input v-model="fiche.phone" type="tel"></label><label class="span-2">Adresse<textarea v-model="fiche.address"/></label><label>SIRET<input v-model="fiche.siret" inputmode="numeric" maxlength="14" placeholder="14 chiffres"></label><label>IBAN<input v-model="fiche.iban" placeholder="Pour le versement des commissions"></label><label class="span-2">Notes<textarea v-model="fiche.notes"/></label></div><p class="field-note" style="margin-top:12px">Votre statut (« {{labels[fiche.status]||fiche.status}} ») et la date de convention sont gérés par Birostweb.</p><button class="btn primary" :disabled="busyFiche" style="margin-top:14px">Enregistrer ma fiche<Icon name="Check"/></button></form></section><section class="panel" style="margin-top:24px"><div class="panel-head"><div><span class="eyebrow">VOTRE ACCÈS</span><h2>MON COMPTE.</h2></div></div><div style="padding:0 24px 24px"><AccountSecurity/></div></section><p class="field-note" style="margin-top:20px">Les commissions sont calculées sur le montant HT réellement encaissé par Birostweb et versées après règlement du client. Pour toute question, contactez Birostweb.</p>
</template>
<div v-else-if="!error" class="skeleton-page" style="margin-top:40px"></div>
</main></template>
