<script setup>
import {ref,computed,watch,onMounted,onUnmounted} from 'vue';import PageTitle from '../components/PageTitle.vue';import Icon from '../components/Icon.vue';import Badge from '../components/Badge.vue';import EmptyState from '../components/EmptyState.vue';import CrudForm from '../components/CrudForm.vue';import Modal from '../components/Modal.vue';import {api,mutate,notify,ui} from '../lib/api.js';import {money,dateLabel,today,downloadCsv} from '../lib/format.js';import {labels} from '../../shared/contracts.js';import {COMMISSION_TIERS} from '../../shared/money.js';
const referrers=ref([]),commissions=ref({rows:[],count:0,stats:{}}),threshold=ref(240000),year=ref(today().slice(0,4)),q=ref(''),status=ref(''),selected=ref(''),page=ref(1),loading=ref(true),error=ref(''),busy=ref(false);
const open=ref(false),kind=ref('referrers'),editing=ref(null),context=ref({}),settling=ref(null),confirm=ref(null),settlement=ref({});
const years=computed(()=>{const n=Number(today().slice(0,4));return [n,n-1,n-2,n-3].map(String);});
const totals=computed(()=>referrers.value.reduce((t,r)=>({due:t.due+r.dueCents,awaiting:t.awaiting+r.awaitingCents,paid:t.paid+r.paidYearCents}),{due:0,awaiting:0,paid:0}));
const flagged=computed(()=>referrers.value.filter(r=>r.das2));
const current=computed(()=>referrers.value.find(r=>r.id===selected.value));
const pages=computed(()=>Math.max(1,Math.ceil(commissions.value.count/25)));
const tiers=COMMISSION_TIERS.map((t,i)=>[`${t.bps/100} %`,t.maxCents===null?`au-delà de ${money(COMMISSION_TIERS[i-1].maxCents,true)}`:i?`de ${money(COMMISSION_TIERS[i-1].maxCents+1,true)} à ${money(t.maxCents,true)}`:`jusqu’à ${money(t.maxCents,true)}`]);
let timer;
async function load(){loading.value=true;try{error.value='';const query=`q=${encodeURIComponent(q.value)}&status=${status.value}&referrerId=${selected.value}&year=${year.value}`;const [people,rows]=await Promise.all([api(`/referrers?year=${year.value}`),api(`/commissions?${query}&page=${page.value}&limit=25`)]);referrers.value=people.rows;threshold.value=people.thresholdCents;commissions.value=rows;}catch(e){error.value=e.message;}finally{loading.value=false;}}
watch([q,status,selected],()=>{page.value=1;clearTimeout(timer);timer=setTimeout(load,180);});watch([page,year,()=>ui.revision],load);onMounted(load);onUnmounted(()=>clearTimeout(timer));
function create(type,record=null,ctx={}){kind.value=type;editing.value=record;context.value=ctx;open.value=true;}
async function changeStatus(c,next){busy.value=true;try{await mutate(`/commissions/${c.id}/status`,'PATCH',{status:next},next==='due'?'Commission exigible : le client a payé.':next==='cancelled'?'Commission annulée.':'Versement annulé.');}catch(e){notify(e.message,'error');}finally{busy.value=false;}}
function askSettlement(c){settling.value=c;settlement.value={paidDate:today(),method:'transfer',reference:`Commission apport affaire - ${c.client.name}`,recordExpense:true};}
async function pay(){busy.value=true;try{await mutate(`/commissions/${settling.value.id}/settle`,'POST',settlement.value,'Commission versée et justificatif enregistré.');settling.value=null;}catch(e){notify(e.message,'error');}finally{busy.value=false;}}
async function remove(){busy.value=true;try{await mutate('/commissions/'+confirm.value.id,'DELETE',undefined,'Commission supprimée.');confirm.value=null;}catch(e){notify(e.message,'error');}finally{busy.value=false;}}
async function archive(r){busy.value=true;try{await mutate('/referrers/'+r.id,'PATCH',{...r,status:r.status==='archived'?'occasional':'archived'},r.status==='archived'?'Apporteur réactivé.':'Apporteur archivé.');}catch(e){notify(e.message,'error');}finally{busy.value=false;}}
async function exportAll(){busy.value=true;try{let rows=[],p=1,count=Infinity;while(rows.length<count){const r=await api(`/commissions?q=${encodeURIComponent(q.value)}&status=${status.value}&referrerId=${selected.value}&page=${p++}&limit=100`);rows.push(...r.rows);count=r.count;if(!r.rows.length)break;}
downloadCsv('birostweb-commissions.csv',['Date encaissement','Apporteur','SIRET','Client','Projet','Assiette HT EUR','Taux %','Commission EUR','Statut','Date de versement','Moyen','Référence'],rows.map(c=>[c.date,c.referrer.name,c.referrer.siret,c.client.name,c.project?.title||'',(c.baseCents/100).toFixed(2),(c.rateBps/100).toFixed(2),(c.amountCents/100).toFixed(2),labels[c.status]||c.status,c.paidDate||'',labels[c.method]||c.method,c.reference]));}catch(e){notify(e.message,'error');}finally{busy.value=false;}}
</script>
<template>
<PageTitle number="11" title="LES APPORTEURS" subtitle="Les mises en relation qui deviennent des clients."><button class="btn" :disabled="busy" @click="exportAll"><Icon name="Download"/>Exporter</button><button class="btn" @click="create('referrers')"><Icon name="UserPlus"/>Ajouter un apporteur</button><button class="btn primary" :disabled="!referrers.length" @click="create('commissions')"><Icon name="Plus"/>Enregistrer une commission</button></PageTitle>
<p v-if="error" class="form-error">{{error}} <button class="text-button" @click="load">Réessayer</button></p>
<section class="metrics-strip"><div><small>À VERSER MAINTENANT</small><strong class="accent">{{money(totals.due)}}</strong></div><div><small>EN ATTENTE D’ENCAISSEMENT</small><strong>{{money(totals.awaiting)}}</strong></div><div><small>VERSÉ EN {{year}}</small><strong>{{money(totals.paid)}}</strong></div></section>
<div class="panel" style="margin-bottom:25px"><div class="panel-head"><div><span class="eyebrow">LE BARÈME</span><h2>8, 9 OU 10 %.</h2></div><span class="eyebrow muted">SUR LE MONTANT HT ENCAISSÉ</span></div><div class="tier-row"><div v-for="[rate,scope] in tiers" :key="rate"><strong>{{rate}}</strong><span>{{scope}}</span></div></div><p class="section-note">La commission porte sur chaque devis signé <strong>et effectivement encaissé</strong> : elle se calcule sur ce que le client vous a réellement versé, et se verse après son règlement. En micro-entreprise, le chiffre d’affaires à déclarer reste le montant total encaissé : la commission n’en est pas déductible.</p></div>
<div class="toolbar"><label class="search-field"><Icon name="Search"/><input v-model="q" placeholder="Un apporteur, un client, une référence…" aria-label="Rechercher une commission"></label><div class="toolbar-end"><select v-model="status" aria-label="Filtrer par statut"><option value="">Tous les statuts</option><option value="awaiting">En attente d’encaissement</option><option value="due">À verser</option><option value="settled">Versées</option><option value="cancelled">Annulées</option></select><select v-model="selected" aria-label="Filtrer par apporteur"><option value="">Tous les apporteurs</option><option v-for="r in referrers" :key="r.id" :value="r.id">{{r.name}}</option></select><select v-model="year" aria-label="Année de référence"><option v-for="y in years" :key="y" :value="y">{{y}}</option></select></div></div>
<div v-if="loading&&!referrers.length" class="skeleton-page"></div>
<EmptyState v-else-if="!referrers.length" title="Personne ne vous apporte encore d’affaires." description="Ajoutez la personne qui vous met en relation, puis enregistrez sa commission dès l’encaissement du client."><button class="btn primary" @click="create('referrers')">Ajouter un apporteur<Icon name="Plus"/></button></EmptyState>
<template v-else>
<section class="panel"><div class="panel-head"><div><span class="eyebrow">CEUX QUI VOUS RECOMMANDENT</span><h2>LES APPORTEURS.</h2></div><span class="eyebrow muted">{{referrers.length}} PERSONNE{{referrers.length>1?'S':''}}</span></div><div class="table-scroll"><table><thead><tr><th>APPORTEUR</th><th>TYPE</th><th>CONVENTION</th><th>CLIENTS</th><th>À VERSER</th><th>VERSÉ EN {{year}}</th><th></th></tr></thead><tbody><tr v-for="r in referrers" :key="r.id" :class="{inactive:r.status==='archived'}"><td><button class="table-title" @click="selected=selected===r.id?'':r.id">{{r.name}}</button><div class="table-sub">{{r.email||r.phone||'Coordonnées à compléter'}}{{r.siret?` · SIRET ${r.siret}`:''}}</div></td><td><Badge :status="r.status"/></td><td>{{r.conventionDate?dateLabel(r.conventionDate,true):'—'}}</td><td>{{r._count.clients}}</td><td class="mono">{{money(r.dueCents,true)}}</td><td class="mono">{{money(r.paidYearCents,true)}}<span v-if="r.das2" class="badge overdue" style="margin-left:8px"><i></i>DAS2</span></td><td><button class="text-button" @click="create('commissions',null,{referrerId:r.id})" style="margin-right:14px">Commission</button><button class="icon-button" aria-label="Joindre un justificatif" title="Joindre la convention ou une preuve de virement" @click="create('documents',null,{referrerId:r.id})"><Icon name="Upload" :size="16"/></button><button class="icon-button" aria-label="Modifier l’apporteur" title="Modifier la fiche" @click="create('referrers',r)"><Icon name="Pencil" :size="16"/></button></td></tr></tbody></table></div>
<div v-if="current" class="section-note" style="margin:0 24px 24px"><div class="row-between"><strong>{{current.name}}</strong><button class="text-button" @click="selected=''">Voir tout le monde<Icon name="X" :size="14"/></button></div><p style="margin-top:10px">{{current.commissionCount}} commission{{current.commissionCount>1?'s':''}} · {{money(current.paidTotalCents,true)}} versés depuis le début · {{current.documents.length}} justificatif{{current.documents.length>1?'s':''}}.<span v-if="current.status==='occasional'"> Mise en relation occasionnelle : la commission reste un revenu que l’apporteur déclare lui-même.</span><span v-else-if="current.status==='regular'"> Apports réguliers : l’apporteur facture ses commissions depuis son propre statut professionnel.</span></p><div v-for="d in current.documents" :key="d.id" class="document-row"><Icon name="FileText" :size="16"/><div><strong>{{d.name}}</strong><small>{{dateLabel(d.createdAt,true)}}</small></div><a class="icon-button" :href="`/api/documents/${d.id}/download`" aria-label="Télécharger le justificatif"><Icon name="Download" :size="16"/></a></div><div class="row-between" style="margin-top:14px"><button class="text-button" @click="create('referrers',current)">Modifier la fiche</button><button class="text-button" @click="archive(current)" :disabled="busy">{{current.status==='archived'?'Réactiver':'Archiver'}}</button></div></div></section>
<p v-if="flagged.length" class="section-note das2-note"><Icon name="TriangleAlert" :size="16"/><span><strong>DAS2 {{year}}</strong> — {{flagged.map(r=>r.name).join(', ')}} {{flagged.length>1?'dépassent':'dépasse'}} {{money(threshold,true)}} versés sur l’année. Cette déclaration se dépose par voie électronique au début du mois de mai de l’année suivante. En dessous du seuil, vous n’avez pas de DAS2 à déposer pour la personne : cela ne dispense pas l’apporteur de déclarer son revenu.</span></p>
<section class="panel" style="margin-top:25px"><div class="panel-head"><div><span class="eyebrow">LE JOURNAL</span><h2>LES COMMISSIONS.</h2></div><span class="eyebrow muted">{{money(commissions.stats.dueCents||0,true)}} À VERSER SUR CE FILTRE</span></div><div class="table-scroll"><table><thead><tr><th>ENCAISSEMENT</th><th>APPORTEUR</th><th>CLIENT / PROJET</th><th>ASSIETTE HT</th><th>TAUX</th><th>COMMISSION</th><th>STATUT</th><th></th></tr></thead><tbody><tr v-for="c in commissions.rows" :key="c.id"><td>{{dateLabel(c.date,true)}}<div class="table-sub" v-if="c.paidDate">Versée le {{dateLabel(c.paidDate,true)}}</div></td><td>{{c.referrer.name}}</td><td><RouterLink class="table-title" :to="'/clients/'+c.clientId">{{c.client.name}}</RouterLink><div class="table-sub">{{c.project?.title||c.label}}</div></td><td class="mono">{{money(c.baseCents,true)}}</td><td class="mono">{{c.rateBps/100}} %</td><td class="mono">{{money(c.amountCents,true)}}</td><td><Badge :status="c.status"/><div class="table-sub" v-if="c.reference">{{c.reference}}</div></td><td class="row-actions"><button v-if="c.status==='awaiting'" class="text-button" @click="changeStatus(c,'due')" :disabled="busy">Client payé</button><button v-else-if="c.status==='due'" class="text-button" @click="askSettlement(c)">Verser<Icon name="Banknote" :size="14"/></button><button v-else-if="c.status==='settled'" class="text-button" @click="changeStatus(c,'due')" :disabled="busy">Annuler le versement</button><button v-if="c.status!=='settled'" class="icon-button" aria-label="Modifier la commission" @click="create('commissions',c)"><Icon name="ArrowUpRight"/></button><button v-if="c.status!=='settled'" class="icon-button" aria-label="Supprimer la commission" @click="confirm=c"><Icon name="Trash2"/></button></td></tr></tbody></table></div><EmptyState v-if="!commissions.rows.length" title="Aucune commission ici." description="Enregistrez-en une dès qu’un client apporté vous a réglé."/><footer class="pagination"><span>{{commissions.count}} commission{{commissions.count>1?'s':''}}</span><div><button class="icon-button outlined" :disabled="page===1" @click="page--" aria-label="Page précédente"><Icon name="ChevronLeft"/></button><span>{{page}} / {{pages}}</span><button class="icon-button outlined" :disabled="page>=pages" @click="page++" aria-label="Page suivante"><Icon name="ChevronRight"/></button></div></footer></section>
<p class="field-note" style="margin-top:18px">Informations indicatives destinées au suivi interne : elles ne remplacent pas l’avis de votre comptable. Conservez pour chaque apport la convention signée, le devis, le montant encaissé, le calcul de la commission et la preuve du virement.</p>
</template>
<CrudForm :open="open" :kind="kind" :record="editing" :context="context" @close="open=false" @saved="load"/>
<Modal :open="!!settling" title="VERSER LA COMMISSION." @close="settling=null"><form v-if="settling" @submit.prevent="pay"><p class="muted">{{settling.referrer.name}} · client {{settling.client.name}} · <strong>{{money(settling.amountCents,true)}}</strong> sur une assiette de {{money(settling.baseCents,true)}} HT.</p><div class="form-grid" style="margin-top:20px"><label>Date du virement<input type="date" v-model="settlement.paidDate" :max="today()" required></label><label>Moyen<select v-model="settlement.method"><option value="transfer">Virement</option><option value="card">Carte</option><option value="cash">Espèces</option><option value="other">Autre</option></select></label><label class="span-2">Libellé / référence<input v-model="settlement.reference" maxlength="200"></label><label class="check-label span-2"><input type="checkbox" v-model="settlement.recordExpense">Enregistrer aussi la dépense dans les finances</label></div><p class="field-note" v-if="settlement.method==='cash'">Un virement bancaire laisse une trace : c’est le justificatif le plus simple à produire en cas de contrôle.</p><div class="form-actions"><button type="button" class="btn" @click="settling=null">Annuler</button><button class="btn primary" :disabled="busy">Confirmer le versement<Icon name="Check"/></button></div></form></Modal>
<Modal :open="!!confirm" title="SUPPRIMER CETTE COMMISSION ?" @close="confirm=null"><p>La commission de {{confirm?.referrer.name}} pour {{confirm?.client.name}} sera supprimée. Cette action est définitive.</p><div class="form-actions"><button class="btn" @click="confirm=null">Conserver</button><button class="btn danger" @click="remove" :disabled="busy">Supprimer</button></div></Modal>
</template>
