<script setup>
import {ref,computed,watch,onMounted} from 'vue';import {api,mutate,session,notify,ui} from '../lib/api.js';import {dateLabel} from '../lib/format.js';import {labels,userCreateSchema} from '../../shared/contracts.js';import PageTitle from '../components/PageTitle.vue';import Icon from '../components/Icon.vue';import Badge from '../components/Badge.vue';import EmptyState from '../components/EmptyState.vue';import Modal from '../components/Modal.vue';
const users=ref([]),referrers=ref([]),loading=ref(true),error=ref(''),open=ref(false),editing=ref(null),busy=ref(false),confirm=ref(null);
const blank=()=>({name:'',email:'',role:'referrer',referrerId:'',password:''});
const form=ref(blank());
const activeReferrers=computed(()=>referrers.value.filter(r=>r.status!=='archived'));
async function load(){loading.value=true;error.value='';const [u,l]=await Promise.allSettled([api('/users'),api('/lookups')]);if(u.status==='fulfilled')users.value=u.value;else error.value=u.reason?.message||'Chargement des comptes impossible.';if(l.status==='fulfilled')referrers.value=l.value.referrers||[];else error.value=error.value||l.reason?.message||'Chargement des apporteurs impossible.';loading.value=false;}
onMounted(load);watch(()=>ui.revision,load);
function add(){editing.value=null;form.value=blank();form.value.referrerId=activeReferrers.value[0]?.id||'';open.value=true;}
function edit(u){editing.value=u;form.value={name:u.name,email:u.email,role:u.role,referrerId:u.referrerId||activeReferrers.value[0]?.id||'',password:''};open.value=true;}
async function save(){busy.value=true;error.value='';try{
  if(editing.value){await mutate('/users/'+editing.value.id,'PATCH',{name:form.value.name,role:form.value.role,referrerId:form.value.role==='referrer'?form.value.referrerId:null},'Compte mis à jour.');}
  else{const data=userCreateSchema.parse({...form.value,referrerId:form.value.role==='referrer'?form.value.referrerId:null});await mutate('/users','POST',data,'Compte créé.');}
  open.value=false;
}catch(e){error.value=e.issues?e.issues.map(i=>i.message).join(' · '):e.message;}finally{busy.value=false;}}
async function remove(){busy.value=true;try{await mutate('/users/'+confirm.value.id,'DELETE',undefined,'Compte supprimé.');confirm.value=null;}catch(e){notify(e.message,'error');}finally{busy.value=false;}}
</script>
<template>
<PageTitle number="12" title="ACCÈS & RÔLES" subtitle="Qui peut se connecter, et ce qu’il peut voir."><button class="btn primary" @click="add"><Icon name="UserPlus"/>Ajouter une personne</button></PageTitle>
<p v-if="error" class="form-error">{{error}} <button class="text-button" @click="load">Réessayer</button></p>
<section class="section-note" style="margin-bottom:24px"><strong>Deux rôles.</strong> Un <em>administrateur</em> a accès à tout le studio. Un <em>apporteur</em> ne voit que son propre espace : ses commissions et les clients qu’il a apportés — rien d’autre. Créez d’abord l’apporteur dans l’onglet <RouterLink class="text-button" to="/apporteurs">Apporteurs</RouterLink>, puis reliez-lui un compte ici.</section>
<div v-if="loading&&!users.length" class="skeleton-page"></div>
<div v-else class="panel"><div class="table-scroll"><table><thead><tr><th>PERSONNE</th><th>RÔLE</th><th>APPORTEUR LIÉ</th><th>2FA</th><th>CRÉÉ LE</th><th></th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td><strong>{{u.name}}</strong><div class="table-sub">{{u.email}}</div></td><td><Badge :status="u.role"/></td><td>{{u.referrer?.name||'—'}}</td><td>{{u.totpEnabled?'Activée':'—'}}</td><td>{{dateLabel(u.createdAt,true)}}</td><td class="row-actions"><button class="icon-button" aria-label="Modifier" @click="edit(u)"><Icon name="ArrowUpRight"/></button><button v-if="u.id!==session.user.id" class="icon-button" aria-label="Supprimer" @click="confirm=u"><Icon name="Trash2"/></button></td></tr></tbody></table></div></div>
<Modal :open="open" :title="editing?'MODIFIER LE COMPTE.':'AJOUTER UNE PERSONNE.'" @close="!busy&&(open=false)"><form @submit.prevent="save"><div class="form-grid"><label class="span-2">Nom<input v-model="form.name" required maxlength="200" autofocus></label><label class="span-2">Email<input v-model="form.email" type="email" required :disabled="!!editing"><span v-if="editing" class="field-note">L’email d’un compte existant ne se change pas ici.</span></label><label>Rôle<select v-model="form.role"><option value="referrer">Apporteur — accès limité</option><option value="admin">Administrateur — accès complet</option></select></label><label v-if="form.role==='referrer'&&activeReferrers.length">Apporteur associé<select v-model="form.referrerId" required><option value="" disabled>Choisir un apporteur</option><option v-for="r in activeReferrers" :key="r.id" :value="r.id">{{r.name}}</option></select></label><p v-if="form.role==='referrer'&&!activeReferrers.length" class="section-note span-2">Aucun apporteur enregistré pour l’instant. Créez d’abord la fiche de la personne dans l’onglet <RouterLink class="text-button" to="/apporteurs">Apporteurs</RouterLink>, puis revenez ici pour lui ouvrir un accès. (Un compte <strong>administrateur</strong>, lui, ne demande aucun apporteur.)</p><label v-if="!editing" class="span-2">Mot de passe initial<input v-model="form.password" type="password" minlength="14" maxlength="128" required autocomplete="new-password"><span class="field-note">14 caractères minimum, refusé s’il figure dans une fuite connue. La personne pourra le changer après connexion.</span></label></div><p v-if="error" class="form-error" role="alert">{{error}}</p><div class="form-actions"><button type="button" class="btn" :disabled="busy" @click="open=false">Annuler</button><button class="btn primary" :disabled="busy||(form.role==='referrer'&&!activeReferrers.length)">{{busy?'Enregistrement…':'Enregistrer'}}<Icon name="Check"/></button></div></form></Modal>
<Modal :open="!!confirm" title="SUPPRIMER CE COMPTE ?" @close="confirm=null"><p>« {{confirm?.name}} » ({{confirm?.email}}) n’aura plus accès. Cette action est définitive ; l’apporteur et ses commissions sont conservés.</p><div class="form-actions"><button class="btn" @click="confirm=null">Conserver</button><button class="btn danger" @click="remove" :disabled="busy">Supprimer</button></div></Modal>
</template>
