<script setup>
import {ref} from 'vue';import {api,session,notify} from '../lib/api.js';import Icon from './Icon.vue';
const name=ref(session.user?.name||''),busyName=ref(false);
const emailForm=ref({email:session.user?.email||'',password:''}),busyEmail=ref(false);
const pwd=ref({current:'',password:'',confirm:''}),busyPwd=ref(false);
const twofa=ref({setup:null,code:'',password:'',busy:false});
async function saveName(){busyName.value=true;try{const r=await api('/auth/profile',{method:'POST',body:{name:name.value}});session.user.name=r.name;notify('Nom mis à jour.');}catch(e){notify(e.message,'error');}finally{busyName.value=false;}}
async function saveEmail(){busyEmail.value=true;try{const r=await api('/auth/email',{method:'POST',body:emailForm.value});session.user.email=r.email;emailForm.value.password='';notify('Adresse de connexion mise à jour.');}catch(e){notify(e.message,'error');}finally{busyEmail.value=false;}}
async function changePassword(){busyPwd.value=true;try{if(pwd.value.password!==pwd.value.confirm)throw new Error('Les mots de passe ne correspondent pas.');await api('/auth/password',{method:'POST',body:{current:pwd.value.current,password:pwd.value.password}});session.user=null;session.csrf='';notify('Mot de passe modifié. Reconnectez-vous.');}catch(e){notify(e.message,'error');}finally{busyPwd.value=false;}}
async function startTotp(){twofa.value.busy=true;try{twofa.value.setup=await api('/auth/2fa/setup',{method:'POST'});}catch(e){notify(e.message,'error');}finally{twofa.value.busy=false;}}
async function enableTotp(){twofa.value.busy=true;try{await api('/auth/2fa/enable',{method:'POST',body:{token:twofa.value.code}});session.user.totpEnabled=true;twofa.value.setup=null;twofa.value.code='';notify('Double authentification activée.');}catch(e){notify(e.message,'error');}finally{twofa.value.busy=false;}}
async function disableTotp(){twofa.value.busy=true;try{await api('/auth/2fa/disable',{method:'POST',body:{password:twofa.value.password,token:twofa.value.code}});session.user.totpEnabled=false;twofa.value.password='';twofa.value.code='';notify('Double authentification désactivée.');}catch(e){notify(e.message,'error');}finally{twofa.value.busy=false;}}
</script>
<template><div class="account-security">
<form @submit.prevent="saveName" class="account-block"><h3>Nom affiché</h3><div class="form-grid"><label class="span-2">Nom<input v-model="name" required maxlength="200"></label></div><button class="btn" :disabled="busyName">Enregistrer le nom<Icon name="Check"/></button></form>
<form @submit.prevent="saveEmail" class="account-block"><h3>Adresse email de connexion</h3><div class="form-grid"><label>Nouvel email<input v-model="emailForm.email" type="email" required autocomplete="username"></label><label>Mot de passe actuel<input v-model="emailForm.password" type="password" required autocomplete="current-password"></label></div><p class="field-note">Cet email sert à vous connecter. Le mot de passe actuel confirme le changement.</p><button class="btn" :disabled="busyEmail">Modifier l’email<Icon name="Check"/></button></form>
<form @submit.prevent="changePassword" class="account-block"><h3>Mot de passe</h3><label>Mot de passe actuel<input v-model="pwd.current" type="password" autocomplete="current-password" required></label><div class="form-grid"><label>Nouveau mot de passe<input v-model="pwd.password" type="password" minlength="14" maxlength="128" autocomplete="new-password" required></label><label>Confirmer<input v-model="pwd.confirm" type="password" minlength="14" autocomplete="new-password" required></label></div><p class="field-note">14 caractères minimum, refusé s’il figure dans une fuite connue. Toutes les sessions seront fermées après modification.</p><button class="btn" :disabled="busyPwd">Modifier le mot de passe<Icon name="Lock"/></button></form>
<div class="account-block"><h3>Double authentification (TOTP)</h3><p class="field-note" style="margin-bottom:14px">Un code à 6 chiffres généré par une application (Google Authenticator, Authy, 1Password…) sera demandé à chaque connexion.</p><template v-if="!session.user.totpEnabled"><button v-if="!twofa.setup" class="btn" :disabled="twofa.busy" @click="startTotp"><Icon name="ShieldCheck"/>Activer la double authentification</button><div v-else><p class="field-note">Scannez ce lien dans votre application, ou saisissez la clé, puis entrez le code obtenu.</p><p style="margin:12px 0;word-break:break-all"><a :href="twofa.setup.otpauth">{{twofa.setup.otpauth}}</a></p><p style="margin:12px 0">Clé : <strong class="mono">{{twofa.setup.secret}}</strong></p><form @submit.prevent="enableTotp" class="form-grid"><label>Code de vérification<input v-model="twofa.code" inputmode="numeric" maxlength="6" placeholder="6 chiffres" required></label><div style="align-self:end"><button class="btn primary" :disabled="twofa.busy">Confirmer l’activation<Icon name="Check"/></button></div></form></div></template><form v-else @submit.prevent="disableTotp"><div class="section-note" style="margin-bottom:16px"><Icon name="ShieldCheck" :size="16"/> La double authentification est active.</div><div class="form-grid"><label>Mot de passe actuel<input v-model="twofa.password" type="password" autocomplete="current-password" required></label><label>Code de vérification<input v-model="twofa.code" inputmode="numeric" maxlength="6" placeholder="6 chiffres" required></label></div><button class="btn danger" :disabled="twofa.busy">Désactiver la double authentification</button></form></div>
</div></template>
