<script setup>
import {computed,ref} from 'vue';import {money} from '../lib/format.js';
const props=defineProps({rows:{type:Array,default:()=>[]}});const hover=ref(null);
const max=computed(()=>Math.max(...props.rows.map(r=>Math.max(r.revenue,r.expenses)),10000)*1.22);
const x=i=>58+i*(820/Math.max(1,props.rows.length-1));const y=n=>220-n/max.value*190;
const points=computed(()=>props.rows.map((r,i)=>`${x(i)},${y(r.revenue)}`).join(' '));const expensePoints=computed(()=>props.rows.map((r,i)=>`${x(i)},${y(r.expenses)}`).join(' '));
const label=k=>new Date(k+(k.length===7?'-01':'')+'T12:00:00Z').toLocaleDateString('fr-FR',k.length===7?{month:'short'}:{day:'numeric',month:'short'});
</script>
<template><div class="revenue-chart"><div class="chart-tooltip" v-if="hover!==null&&rows[hover]"><strong>{{label(rows[hover].key)}}</strong> · {{money(rows[hover].revenue,true)}} encaissés</div><svg viewBox="0 0 900 270" role="img" aria-label="Évolution des encaissements et des dépenses sur la période"><g v-for="n in [0,1,2,3]" :key="n"><line x1="58" x2="880" :y1="220-n*63" :y2="220-n*63" class="chart-grid"/><text x="0" :y="224-n*63" class="chart-label">{{money(Math.round(max*n/3))}}</text></g><polygon v-if="rows.length" :points="`58,220 ${points} ${x(rows.length-1)},220`" fill="var(--accent)" opacity=".055"/><polyline :points="expensePoints" fill="none" stroke="var(--line)" stroke-width="2" stroke-dasharray="5 5"/><polyline :points="points" fill="none" stroke="var(--accent)" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/><g v-for="(row,i) in rows" :key="row.key"><circle :cx="x(i)" :cy="y(row.revenue)" :r="hover===i?6:3" fill="var(--accent)"/><rect :x="x(i)-10" y="20" width="20" height="220" fill="transparent" tabindex="0" :aria-label="`${label(row.key)} : ${money(row.revenue,true)}`" @mouseenter="hover=i" @mouseleave="hover=null" @focus="hover=i" @blur="hover=null"/><text v-if="rows.length<=13||i%Math.ceil(rows.length/7)===0" :x="x(i)" y="250" text-anchor="middle" class="chart-label">{{label(row.key)}}</text></g></svg></div></template>
